name: .NET Core

on:
  push:
    branches: [ master, 'dev_6.0' ]
  pull_request:
    branches: [ master, 'dev_6.0' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        source-url: https://www.nuget.org/api/v2/package
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Install dependencies
      run: dotnet restore src/sample/Leon.XXX.Api/Leon.XXX.Api.csproj
    - name: Build
      run: dotnet build src/sample/Leon.XXX.Api/Leon.XXX.Api.csproj --configuration Release --no-restore
    - name: Test
      run: dotnet test src/sample/Leon.XXX.Api/Leon.XXX.Api.csproj --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack src/NetProMicroservice.sln --no-restore  --output publish -c Release
    - name: Push Pack
      run: dotnet nuget push publish/*.nupkg -s https://www.nuget.org/api/v2/package   --skip-duplicate
